spring.application.name=api

spring.datasource.url=jdbc:postgresql://localhost:5432/lumen
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=lumen
spring.datasource.password=lumen
spring.jpa.hibernate.ddl-auto=update

spring.security.oauth2.resourceserver.jwt.issuer-uri=${AUTH0_ISSUER_URI:}
